### ISSUE TITLE
Add the discord link in the README

### ISSUE THREAD

**Issue by rara4** [ElZozor/ut3_calendar#16]
For some reason the discord server is advertised, but there is no way to access it. I couldn't find a link in the readme.
Any way to fix it? 
(If the discord server doesn't exist anymore, might as well remove that part in the readme)

Thanks !

**Comment by axellaffite** [comment]
Hi !
Sorry I didn't see your issue, I haven't worked for months on this project.

It's fixed now, thank you for this information 😊
