### ISSUE TITLE
Bug: la vue "Visibilité des cours" ne s'affiche pas en mode authentifié

### ISSUE THREAD

**Issue by erikmd** [ElZozor/ut3_calendar#20]
Bonjour @axellaffite,

je crois avoir trouvé un bug (reproduit sur un smartphone Samsung avec Android 10 et par un collègue du dept-info) :

* Dans le mode authentifié (si on appuie sur la roue dentée, puis on rentre ses infos de login Celcat),  
  la fonctionnalité de sélection des cours ne fonctionne pas :
  un clic sur l'icône en forme d'œil en haut **affiche juste le titre "Visibilité des cours"** (en bas, sans afficher le reste),  
  donc il est impossible de sélectionner des cours à filtrer.
* En revanche, dans le mode non authentifié (si l'on enlève ses infos de login), cela fonctionne bien.

**Comment by axellaffite** [comment]
Bonjour,

Je n'ai pas constaté ce soucis de mon côté.
La fonctionnalité s'appuie sur les événements récupérés et mis en cache. Est-ce que des événements sont présent dans le calendrier même en mode authentifié ?
