### ISSUE TITLE
Absence des amphis dans les salles libres

### ISSUE THREAD

**Issue by BENICHN** [ElZozor/ut3_calendar#21]
Bonjour, déjà merci pour cette appli que je trouve bien faite et très utile.

J'ai l'impression que dans l'onglet des salles libres, on ne retrouve pas les amphis, ce qui est dommage parce que ce serait très pratique aussi.
Probablement le saviez vous déjà, peut être une impossibilité technique...
En tout cas si y avait moyen d'avoir cette fonctionnalité ce serait génial.

**Comment by axellaffite** [comment]
Bonjour,

L'application consomme uniquement cette API : https://github.com/goulinkh/rooms-finder
Les modifications sont donc à faire de ce côté cependant je ne suis pas le mainteneur du repo.

**Comment by BENICHN** [comment]
Je suis allé voir sur le site https://rooms-finder.goulin.fr/ mis à disposition par l'auteur de l'API, et les amphis apparaissent bien.
J'ai regardé plus attentivement sur l'appli et en fait les amphis apparaissent, mais uniquement pour le bâtiment 3TP2 (donc en majorité ils n'apparaissent pas)

**Comment by axellaffite** [comment]
Ah oui en effet, mais il faut sélectionner manuellement l'amphi sinon il n'apparaissent pas, l'application elle récupère la liste sans choisir de batiment en particulier.
Je regarderai ça quand je pourrai

**Comment by axellaffite** [comment]
Après, il s'agit d'une issue qui selon moi concerne plutôt l'API qui devrait inclure les amphis sans avoir à les choisir manuellement

**Comment by BENICHN** [comment]
D'accord, je vous avoue que je ne connais pas cette API.
En tout cas j'admire votre réactivité parce que maintenir une application c'est pas ce qui a de plus exaltant.

**Comment by axellaffite** [comment]
@goulinkh

**Comment by goulinkh** [comment]
@BENICHN Pouvez-vous donner un exemple d'amphi qui n'apparaît pas, je viens de tester pour [le bâtiment U4](https://rooms-finder.api.goulin.fr/rooms?building=U4) et on voie bien les amphithéâtres dans la liste des salles

**Comment by BENICHN** [comment]
@goulinkh Désolé pour ce petit retard. En fait, sur l'appli, les amphis apparaissent uniquement pour le bâtiment 3TP2, mais sur le site https://rooms-finder.goulin.fr/, on les voit bien tous

**Comment by axellaffite** [comment]
@goulinkh Si on liste les heures où les salles sont disponibles pour un bâtiment donné, les amphis n'apparaissent pas :  [https://rooms-finder.api.goulin.fr/?place=U4](https://rooms-finder.api.goulin.fr/?place=U4)

Cependant, si on liste les salles de ce bâtiment, les amphis sont bien présents

**Comment by goulinkh** [comment]
@BENICHN Cela devrait être bon, je viens de règler le problème!

**Comment by BENICHN** [comment]
oui en effet ils apparaissent tous maintenant. merci beaucoup !
