### ISSUE TITLE
Décalage dans les horaires des salles libres

### ISSUE THREAD

**Issue by BENICHN** [ElZozor/ut3_calendar#22]
Rebonjour, j'ai constaté un autre problème au niveau des salles libres, plus embêtant que celui des amphis, mais qui devrait être assez simple à corriger. Il y a tout simplement un décalage de 2h entre les horaires du site https://rooms-finder.goulin.fr/ (les bonnes) et les horaires données par l'appli, comme le montre cette capture d'écran.

![Screenshot_20211014-143449.jpg](https://user-images.githubusercontent.com/26910885/137630158-55744c08-f471-4898-9044-0639d31046c1.jpg)

**Comment by axellaffite** [comment]
Effectivement, je m'en charge dés que possible

**Comment by axellaffite** [comment]
Fixed by #25 
Thanks @BENICHN for your help :smile:
