### ISSUE TITLE
Application closes immediately after lauching

### ISSUE THREAD

**Issue by akhaten** [ElZozor/ut3_calendar#31]
Hi,

It seems that the latest version of the application (v2.4.1) available on google play does not work.
The application closes immediately after lauching.

Best regard!

----

Bonjour,

Il semblerait que la dernière version de l'application  (v2.4.1) disponible sur Google Play ne fonctionne pas.
L'application se ferme immédiatement après l'ouverture.

Cordialement.

---
Material Infos :
```
Android : v13
One Ui : v5.1
```

**Comment by axellaffite** [comment]
Hi there,

The issue has probably been resolved by [#30](https://github.com/axellaffite/ut3_calendar/pull/30).

The update is still pending for verification on the playstore, though.

I keep your issue open until I'm sure it is resolved.

Thank you for reporting the issue :)
